# Generated by Django 5.1.6 on 2025-02-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=125, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
